name: featgraph
channels:
  - conda-forge
  - chromaticisobar
dependencies:
  - python>=3.7,<3.9
  - JPype1
  - requests
  - chromatictools
  - sortedcontainers
  - more-itertools
  - networkx
  - scipy
  - numpy
  - pymc3
  - arviz>=0.11.4
  - mkl-service
  - matplotlib
  - seaborn
  - tqdm
