name: featgraph
channels:
  - conda-forge
  - chromaticisobar
dependencies:
  - python>=3.7
  - JPype1
  - requests
  - chromatictools
  - sortedcontainers
  - more-itertools
  - networkx
  - scipy
  - numpy
